iphone_8_plus_case:
  - 蘋果8plus手機殼
  - iphone 8 plus手機保護殼
  - Iphone 8 plus case
wireless_bluetooth_earphone:
  - 藍牙無線耳機
  - 專業藍牙無線耳機
  - Wireless Bluetooth earphone
apple_wireless_charger:
  - iphone 8 無線充電
  - Apple wireless charger for iphone X
  - 蘋果無線充電器
  - 無線充電器蘋果

